version: "3.9"

services:
  traefik:
    image: traefik:v3.6.1
    command:
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.network=demo_public
      - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8080
      - --api.dashboard=true
      - --log.level=DEBUG
      - --accesslog=true
    ports:
      - target: 80
        published: 8090
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.swarm.network=demo_public
        - traefik.http.routers.traefik.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)
        - traefik.http.routers.traefik.entrypoints=traefik
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.dummy-svc.loadbalancer.server.port=9999

  frontend:
    image: swarm-demo-frontend:latest
    networks:
      - public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.network=demo_public
        - traefik.http.routers.frontend.rule=PathPrefix(`/`)
        - traefik.http.routers.frontend.entrypoints=web
        - traefik.http.routers.frontend.priority=1
        - traefik.http.services.frontend.loadbalancer.server.port=80

  api-gateway:
    image: swarm-demo-api-gateway:latest
    environment:
      SERVICE_NAME: api-gateway
      DATA_SERVICE_URL: http://data-service:8000
      LOAD_SERVICE_URL: http://load-service:8000
      ML_SERVICE_URL: http://ml-service:8000
      HTTP_TIMEOUT_SECONDS: 15
    networks:
      - public
      - app_net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.network=demo_public
        - traefik.http.routers.api-gateway.rule=PathPrefix(`/api`) || PathPrefix(`/health`)
        - traefik.http.routers.api-gateway.entrypoints=web
        - traefik.http.routers.api-gateway.priority=100
        - traefik.http.services.api-gateway.loadbalancer.server.port=8000

  load-service:
    image: swarm-demo-load-service:latest
    environment:
      SERVICE_NAME: load-service
    networks:
      - app_net
    deploy:
      replicas: 1

  ml-service:
    image: swarm-demo-ml-service:latest
    environment:
      SERVICE_NAME: ml-service
      GPU_NODE: "true"
    secrets:
      - source: redis_app_password
        target: redis_app_password
      - source: redis_app_username
        target: redis_app_username

    networks:
      - app_net
    deploy:
      replicas: 1

  data-service:
    image: swarm-demo-data-service:latest
    configs:
      - source: pg_db_name
        target: /run/configs/pg_db_name
      - source: pg_db_user
        target: /run/configs/pg_db_user
    secrets:
      - source: pg_password
        target: pg_password
    networks:
      - app_net
    deploy:
      replicas: 1


  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - source: pg_password
        target: pg_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    networks:
      - app_net
    volumes:
      - redis_data:/data
    configs:
      - source: redis_conf
        target: /usr/local/etc/redis/redis.conf
    secrets:
      - source: redis_app_password
        target: redis_app_password
      - source: redis_app_username
        target: redis_app_username
    command: >
      sh -c '
        set -eux
        ls -l /run/secrets
        APP_PASS="$$(cat /run/secrets/redis_app_password)"
        echo "Password loaded"
        APP_USERNAME="$$(cat /run/secrets/redis_app_username)"
        echo "Secrets loaded"
        printf "%s\n" \
          "user default off" \
          "user $$APP_USERNAME on >$$APP_PASS ~mlcache:* +get +set +del +expire +ttl +pttl +exists +ping" \
          > /usr/local/etc/redis/users.acl
        echo "Starting redis"
        exec redis-server /usr/local/etc/redis/redis.conf
      '

networks:
  public:
    name: demo_public
    driver: overlay
    attachable: true
  app_net:
    name: demo_app_net
    driver: overlay
    attachable: true

volumes:
  pg_data:
  redis_data:

configs:
  pg_db_name:
    external: true
  pg_db_user:
    external: true
  redis_conf:
    external: true

secrets:
  pg_password:
    external: true
  redis_app_password:
    external: true
  redis_app_username:
    external: true